# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: run tests
          command: |
            # . venv/bin/activate
            pipenv run pytest
      - store_artifacts:
          path: test-reports
          destination: test-reports